Support Ubuntu 20.04
sous-chefs/atom pull request #68
Opened 2021-04-12 05:11 UTC by MarkGibbons

# Description

Describe what this change achieves

## Issues Resolved

List any existing issues this PR resolves

## Check List

- [ ] All tests pass. See TESTING.md for details.
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable.

2021-04-12 05:11 UTC, kitchen-porter commented
<!--
  1 Error: Please include a CHANGELOG ent...
  0 Warnings
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please include a CHANGELOG entry.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2021-04-22 20:41 UTC, ramereth requested changes

2021-04-22 20:41 UTC, ramereth commented on recipes/debian.rb
> +# end
If we're no longer using this repo, then we should remove it from the code and update the test to check the new repo.

2021-05-08 03:58 UTC, MarkGibbons commented
I fixed up the test and removed the left. over comments.  I think this one is ready.

2021-05-08 22:37 UTC, MarkGibbons commented
Added 2104

2021-05-11 19:59 UTC, ramereth commented
> Can we add 21.04 support too whilst you're there?

I really don't like the idea of adding non-LTS releases to testing as it's a pain to update every 6 months on every cookbook

2021-05-15 03:23 UTC, MarkGibbons commented
Added 21.04 to kitchen.yml.  Should be ready.

2021-05-17 08:50 UTC, damacus approved these changes

2021-05-17 08:50 UTC, merged

2021-05-17 08:50 UTC, kitchen-porter commented
Released as: [0.5.0](https://github.com/sous-chefs/atom/releases/tag/0.5.0)